config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 15, maximum: 250 }
  validates :description, presence: true, length: { minimum: 20, maximum: 4096 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def edit; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    title = @article.title
    @article.destroy
    flash[:notice] = "Article «#{title}» was successfully deleted; bon voyage!"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
  def about; end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Problem!</h2>
  <p>
    The following errors prevented the article from being saved:
  </p>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end  %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an existing Article</h1>

<%= render 'form' %>

<p><%= link_to '[Cancel]', articles_path %></p>

app/views/articles/index.html.erb
<h1>Articles Overview</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td>[ <%= link_to 'Show', article_path(article) %>
          | <%= link_to 'Update', edit_article_path(article) %>
          | <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>  ]</td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Add New', new_article_path %> | <%= link_to 'Home', root_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render 'form' %>

<p><%= link_to '[No thanks]', articles_path %></p>

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<table>
  <tbody>
    <tr>
      <td><strong>Title</strong></td>
      <td>:</td>
      <td><%= @article.title %></td>
    </tr>
    <tr>
      <td colspan="3"><strong>Description</strong></td>
    </tr>
    <tr>
      <td></td>
      <td colspan="2"><%= @article.description %></td>
    </tr>
  </tbody>
</table>
<br/>
<table>
  <tbody>
    <tr>
      <td><%= link_to '[Edit]', edit_article_path(@article) %></td>
      <td><%= link_to '[Toss]', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to '[Back]', articles_path %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UdemyRorAlphaLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<hr/>
<p>
  This is my Ruby on Rails project.
  It is about <%= link_to 'articles', articles_path %> for a blog-like website.
  I coded along with Mashrur Hossain from Udemy.
</p>
<hr/>
<%= link_to '[HOME]', root_path %>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>
  This is the home page of my awesome Alpha Log app.
</p>
<p>
  Wait a minute: was that Alpha <b>b</b>log???
</p>
<p>
  Oh well ... ¯\_(ツ)_/¯
</p>
<p>
  Click <%= link_to 'here', articles_path %> to go to the <b>Articles Listing</b>.
</p>
<p>
  Click <%= link_to  'here', about_path %> to learn more about this project.
</p>